### ISSUE TITLE
.gitignore

### ISSUE THREAD

**Issue by JB-Gamercool** [Pandarox-Product/pandarox-bot#3]
### Question to @SebastienWeb about the **.gitignore**
Why don't add the parsers/linters configuration json files into the [.gitignore](https://github.com/Pandarox-Product/pandarox-bot/blob/main/.gitignore) file ?
There aren't useful for the code, only for the developers, you (@SebastienWeb) in this case.
- Files concerned : 
  - [.eslintrc.json](https://github.com/Pandarox-Product/pandarox-bot/blob/main/.eslintrc.json)
  - [.prettierrc.json](https://github.com/Pandarox-Product/pandarox-bot/blob/main/.prettierrc.json)
  - [.stylelintrc.json](https://github.com/Pandarox-Product/pandarox-bot/blob/main/.stylelintrc.json)

**Comment by SebastienWeb** [comment]
Simply that if there are several of us working together, everyone can see the rules for naming the code and can therefore make up their minds about it. These are basic and simple rules and therefore not being a personal configuration it can be set for everyone. Because the concern of adding these files in the git Ingnore it can happen that other developers code their own style and therefore the teamwork can end up in nomentaclure shift. 

Translated with www.DeepL.com/Translator (free version)

**Comment by JB-Gamercool** [comment]
Understood, I didn't saw that the parsers/linters were in the devDependencies of [package.json](https://github.com/Pandarox-Product/pandarox-bot/blob/main/package.json).
Thank you for your answer, I'll apply these rules in the future !
###### Note : I close this issue
